### ISSUE TITLE
Error if two streams are opened in parallel

### ISSUE THREAD

**Issue by yusefnapora** [multiformats/js-multistream-select#33]
I think this is the right repo for this 😄 

I recently encountered an error (in https://github.com/mediachain/aleph/pull/157) when trying to open two streams to a javascript peer in parallel (using `Promise.all`, since we wrap the libp2p dial code with Promises).  After changing the code to open the second stream after the first one opens, everything works fine.

At the time I was getting a Zlib error:

```
Uncaught Error: incorrect header check
      at Zlib._handle.onerror (zlib.js:370:17)
```

But now for some reason checking out the [commit just prior to the fix](https://github.com/mediachain/aleph/commit/a5f5de74dbc19e97e461aa536d84d9dd9c8148da) I'm getting this much more helpful error:

<details>
<summary>stack trace</summary>

```
Uncaught Error: Callback was already called.
      at node_modules/async/internal/onlyOnce.js:9:32
      at select (node_modules/multistream-select/src/dialer/index.js:23:16)
      at node_modules/pull-handshake/index.js:10:5
      at node_modules/pull-handshake/index.js:23:13
      at callback (node_modules/pull-pushable/index.js:69:7)
      at read (node_modules/pull-pushable/index.js:21:15)
      at node_modules/pull-cat/index.js:7:11
      at Array.forEach (native)
      at abortAll (node_modules/pull-cat/index.js:6:7)
      at next (node_modules/pull-cat/index.js:22:9)
      at node_modules/pull-cat/index.js:37:7
      at Stream.onError (node_modules/stream-to-pull-stream/index.js:47:16)
      at Stream._handleRST (node_modules/spdy-transport/lib/spdy-transport/stream.js:280:10)
      at Stream._handleFrame (node_modules/spdy-transport/lib/spdy-transport/stream.js:126:10)
      at Connection._handleFrame (node_modules/spdy-transport/lib/spdy-transport/connection.js:326:12)
      at Parser.<anonymous> (node_modules/spdy-transport/lib/spdy-transport/connection.js:158:10)
      at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:217:18)
      at Parser.Readable.push (node_modules/readable-stream/lib/_stream_readable.js:176:10)
      at Parser.Transform.push (node_modules/readable-stream/lib/_stream_transform.js:123:32)
      at next (node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:52:12)
      at node_modules/spdy-transport/lib/spdy-transport/protocol/spdy/parser.js:57:5
      at Parser.onRSTFrame (node_modules/spdy-transport/lib/spdy-transport/protocol/spdy/parser.js:377:3)
      at Parser.onFrameBody (node_modules/spdy-transport/lib/spdy-transport/protocol/spdy/parser.js:141:10)
      at Parser.execute (node_modules/spdy-transport/lib/spdy-transport/protocol/spdy/parser.js:50:8)
      at Parser._consume (node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:92:8)
      at node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:60:12
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

</details>

I'm not sure why the error changed, but it seems like maybe there needs to be some kind of mutex or lock around the connection when the multistream handshake is in progress?  It seems like messages from both dial attempts were probably getting interleaved and mucking things up.

It looks like we're on `multistream-select` 0.13.0 btw.  Let me know if I can provide any more details.

**Comment by diasdavid** [comment]
For the first error: Are these two peers, one in the browser, one in Node.js? You need to use the right browserify-zlib (still getting it to be the right one by default: https://github.com/substack/node-browserify/issues/1672)

For the problem as a whole: Yes, we need to make swarm a state machine https://github.com/libp2p/js-libp2p-swarm/issues/24, otherwise it will get confused and open two sockets at the same time. After the first dial, you can open in parallel as many as you want, it is just the first that needs to be isolated.

**Comment by yusefnapora** [comment]
Actually both peers were running in the same node process, although that's good to know for future reference.  It sounds like the "dial locks" in the swarm issue are the solution, so I'll close this one.  Thanks :)
